- .gitignore
- client/WarFare/WarFare.dsp
- client/WarFare/WarFare.mak
- client/WarFare/WarFare.sln
- client/WarFare/WarFare.vcxproj
- client/WarFare/WarFare.vcxproj.user
- client/WarFare/WarFare_BUILD.vcxproj
Break points still not working yet, but debugging does.
> Allow Debugging WarFare / Client.

- client/N3FE/N3FE.sln
- client/N3FE/N3FE.vcxproj
- client/N3FE/N3FE.vcxproj.filters
- client/N3FE/N3FE.vcxproj.user
- client/N3FE/N3FE_BUILD.vcxproj
This is probably an older version of N3FXE or something. I haven't
checked, but it misses implementation and doesn't compile.
> Build N3FE ?? with VS22.

- src/engine/N3Base/N3Log.cpp
- src/engine/N3Base/N3Log.h
- src/game/KnightOnLine.vcxproj
- src/game/KnightOnLine.vcxproj.filters
- src/game/Main.cpp
- src/game/StdAfx.h
This PR integrates spdlog with a nice wrapper against it.
Ideally all logging should go through it to centralize everything.
> Integrate spdlog for better logging.

- src/game/GameProcMain.cpp
- src/game/UIChat.cpp
- src/game/UIQuestTalk.cpp
- src/game/UIVarious.cpp
Various small fixes to get the game more stable.
> Fix wrap gate listing, UIVarious UpdateKnightsDuty and UIQuestTalk

- src/engine/N3Base/My_3DStruct.h
- src/game/GameBase.cpp
- src/game/GameBase.h
- src/game/GameDef.h
- src/game/Main.cpp
Implement loading strings from Texts.tbl. If resource ID not found, we issue a warning in DEBUG mode and attempting to fall back to the old approach.
> Implement loading strings from Texts.tbl.

- src/engine/N3Base/N3UIEdit.cpp
- src/engine/N3Base/N3UIEdit.h
- src/game/Main.cpp
https://github.com/stevewgr/ko/issues/51
> Fixed UI inputs caret position and focus

- .github/workflows/build.yml
- README.md
- build.cmd
- config.cmd
Thanks to @ko4life-psko for helping us manage the project better, we have now transferred the repositories to have a better home.
> Transfer domain to ko4life-net

- src/engine/N3Base/DFont.cpp
- src/engine/N3Base/N3UIBase.cpp
- src/engine/N3Base/N3UIBase.h
- src/engine/N3Base/N3UIString.cpp
- src/engine/N3Base/N3UIString.h
- src/game/APISocket.cpp
- src/game/GameDef.h
- src/game/GameProcLogIn.cpp
- src/game/GameProcMain.cpp
- src/game/UIClassChange.cpp
- src/game/UILogin.cpp
- src/game/UILogin.h
- src/game/UINPCChangeEvent.cpp
- src/game/UINationSelectDlg.cpp
- src/game/UIPartyBBS.cpp
- src/game/UIPartyOrForce.cpp
- src/game/UIQuestMenu.cpp
- src/game/UISkillTreeDlg.cpp
- src/game/UIStateBar.cpp
- src/game/UIVarious.cpp
Note that we'll merge this for now, even though it's not cleaned up yet, just because there is a lot of work to do on UIs that it will be easier to to manage that way.
We'll fix and implement UI logic as we go.
> WIP: 1264 UIs.

- src/game/GameDef.h
- src/game/KnightOnLine.vcxproj
- src/game/KnightOnLine.vcxproj.filters
- src/game/UIMsgBoxOkCancel.cpp
- src/game/UIMsgBoxOkCancel.h
- src/game/UINationSelectDlg.cpp
- src/game/UINationSelectDlg.h
This PR implement v1264 Nation Select UIFs to its full capacity:
+ Implement UIMsgBoxOkCancel dialog for confirmation.
+ Implement nation select transition when switching nation.
+ Implement loading sound. This needs to be triggered from procedures.
Cherry-picked few changes from @xGuTeK [PR](https://github.com/ko4life-net/ko/pull/118)'s changes: https://github.com/ko4life-net/ko/commit/77f073f6a91c491935d10545b6b429e7ec9ce33a
> Implements v1264 Nation Select UIFs to its full capacity, as well as UIMsgBoxOkCancel dialog

- .gitignore
- config.cmd
Just to keep everything in one place, to not confuse newbies too much.
> Fetch db in src dir as well.

- src/game/GameProcMain.cpp
Fix formatting issues with GameProcMain.
> Fix formatting issues with GameProcMain.

- src/tool/Option/Option.rc
- src/tool/Option/Option.vcxproj.user
- src/tool/Option/OptionDlg.cpp
- src/tool/Option/OptionDlg.h
- src/tool/Option/resource.h
Fixed Option
Delete what is not required to open that, all registry disabled and deleted.
-Loading all from option.ini. (For early stage it will be good, later we can updated)
-Translate from Korean to English (Buttons, and most required things, still some left.)
-Loading/Save version from server.ini Version
-Adding some information in header files, which settings is for and what is does, and how it is work.
Working well.
> Fixed Option

- src/game/GameProcMain.cpp
- src/game/GameProcMain.h
- src/game/UINotice.cpp
- src/game/UINotice.h
Fixes close button and correct position for NoticeBox
> Implements v1264 UI Notice

- src/engine/N3Base/N3Eng.cpp
- src/engine/N3Base/N3Eng.h
- src/game/GameProcCharacterCreate.cpp
- src/game/GameProcCharacterSelect.cpp
- src/game/GameProcLogIn.cpp
- src/game/GameProcMain.cpp
- src/game/GameProcNationSelect.cpp
- src/game/GameProcedure.cpp
- src/game/GameProcedure.h
- src/game/KnightOnLine.vcxproj
- src/game/KnightOnLine.vcxproj.filters
- src/game/LocalInput.cpp
- src/game/Main.cpp
- src/game/N3UIDebug.cpp
- src/game/N3UIDebug.h
- src/game/PlayerBase.cpp
- src/game/UIEndingDisplay.cpp
- src/game/UILoading.cpp
- src/game/WarMessage.cpp
Resolves https://github.com/ko4life-net/ko/issues/112
This PR integrates and implements ImGui for better debugging experience.
I also implemented couple of nice features to the custom window, such as graph for FPS, as well as controling the view distance. Note that this also gets ride of the annoying debug white text on the left top corner.
Special thanks to @ko4life-psko for suggesting to use it and for answering all my questions :D🕺 
Note that the ko-vendor PR needs to be merged first before triggering test build: https://github.com/ko4life-net/ko-vendor/pull/10
Some pictures:
> Implement ImGui window rendering for debugging.

- src/game/Main.cpp
Fix temporarily imgui windows procedure.
Still need to figure out how to handle ImGui's stuff for Windows procedure without interfering with packet processing.
> Fix temporarily imgui windows procedure.

- src/engine/N3Base/N3Sun.cpp
Resolves https://github.com/ko4life-net/ko/issues/167
This bug occurs only when sun rises. I needed to revert some changes from previous PR (#159) with sun and it works :)
> Fixed sun issue when sun rises #167

- src/game/GameProcMain.cpp
- src/game/GameProcMain.h
It allows the player's camera to rotate 180 degrees when the middle mouse button is clicked.
-  https://github.com/ko4life-net/ko/issues/93
> 180 degree camera rotation arrangement.

- src/tool/Launcher/Launcher/Launcher.vcxproj.user
Adding an extra `..\`  so the debug dir matches with what is to be expected.
> Updating the LocalDebuggerWorkingDirectory to match where the directory is located

- src/game/GameProcMain.cpp
- src/game/GameProcMain.h
This PR is continuitaiton of @selcukcukur (thank you for the efforts nevertheless) previous PR (https://github.com/ko4life-net/ko/pull/172) where the camera rotation was not animated. Now we implement it exactly as per official when the user clicks the middle mouse button, the camera rotates 180 degrees with animation.
This also resolves the following ticket: https://github.com/ko4life-net/ko/issues/93
> Implement 180 degrees animated camera rotation

- src/game/N3UIDebug.cpp
- src/game/N3UIDebug.h
It does'nt change the weather and time on the server
Improved it further (@stevewgr):
> Widget to debug game day and night cycle and weather

- .github/workflows/deploy.yml
- src/server/Ebenezer/EbenezerDlg.cpp
Adding workflow to deploy to remote windows server.
💔Thank you!
> Adding deploy workflow and removing confirmation box from Ebenezer

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- src/engine/N3Base/N3UIString.cpp
- src/game/CountableItemEditDlg.cpp
- src/game/GameBase.cpp
- src/game/GameCursor.cpp
- src/game/N3UIWndBase.cpp
- src/game/UIHotKeyDlg.cpp
- src/game/UIImageTooltipDlg.cpp
- src/game/UILoading.cpp
- src/game/UIPartyBBS.cpp
- src/game/UISkillTreeDlg.cpp
- src/game/UIStateBar.cpp
- src/game/UITradeEditDlg.cpp
- src/game/UITradeSellBBS.cpp
- src/game/UITransactionDlg.cpp
- src/game/UIWareHouseDlg.cpp
This PR partially addressing this ticket: https://github.com/ko4life-net/ko/issues/81
I also updated the linting job to only run if pushed to master, PR created or changes were pushed there. Also gave the option to manually run it using workflow dispatch.
> Cleanup more sprintf usages with C++20 std::format and std::to_string.

- src/game/APISocket.cpp
- src/game/APISocket.h
- src/game/GameProcCharacterCreate.cpp
- src/game/GameProcedure.cpp
- src/tool/Launcher/Launcher/APISocket.cpp
- src/tool/Launcher/Launcher/APISocket.h
- src/tool/Launcher/Launcher/LauncherDlg.cpp
Adding mutex around packet queue to avoid exception being throw when popping packets off the queue.
> Adding mutex around packet queue

- src/engine/N3Base/N3FXPartParticles.cpp
Fixing commit message from the following PR: https://github.com/ko4life-net/ko/pull/209
> Fix CN3FXPartParticles::Duplicate bug with particles gather point.

- src/game/UITransactionDlg.cpp
Fixing commit message from the following PR: https://github.com/ko4life-net/ko/pull/204
> Fix UITransactionDlg rendering bug when purchasing items.

- config.cmd
Bump db version from 1.0.2 to 1.1.0.
Thanks @twostars for helping out with testing! 🚀
> Bump db version from 1.0.2 to 1.1.0.

- config.cmd
Bump db version from 1.1.0 to 1.1.1.
> Bump db version from 1.1.0 to 1.1.1.

- config.cmd
Bump ko-db version from 1.1.1 to 1.1.2.
> Bump ko-db version from 1.1.1 to 1.1.2.

- .gitmodules
- config.cmd
Initialize sub projects as submodules.
Many years ago on some project I remember using git submodules and I disliked it due to messing with local changes when git status / git add or accidently resetting work on a submodule. Because we can specify `shallow` and `depth` in the gitmodules config file, I decided giving it another chance as it seems to fit well for our use case.
Also thank you @twostars for suggesting to use submodules.
> Initialize sub projects as submodules.

- src/engine/N3Base/N3Log.cpp
- src/engine/N3Base/N3Log.h
- src/game/KnightOnLine.vcxproj
- src/game/Main.cpp
- src/tool/N3Viewer/N3Viewer.vcxproj
- src/tool/N3Viewer/N3Viewer.vcxproj.filters
This pull request refactors the logging configuration to enhance flexibility and performance across different projects. The changes address the following needs and improvements:
1. **Flexibility Across Projects**:
- This class is utilized by multiple projects, each with unique requirements.
- Some projects do not need `spdlog` as a dependency, but instead, only require the N3Base engine (e.g., our tools).
- To accommodate these varied needs, the implementation is made more configurable through the use of preprocessor directives.
2. **Enhanced Configurability**:
- By introducing macros, we can control the inclusion of logging code based on project-specific needs.
- When logs are disabled in release mode, no logging code will be generated. This optimization helps in improving the …
> Refactor Logging Configuration for Flexibility and Performance
