ko4life-net/ko

src/engine/N3Base/N3AnimControl.h
src/engine/N3Base/N3BaseFileAccess.cpp
src/engine/N3Base/N3Eng.cpp
src/engine/N3Base/N3SkyMng.h
src/engine/N3Base/N3UIBase.cpp
src/engine/N3Base/N3UIButton.cpp
src/engine/N3Base/N3UIEdit.cpp
src/engine/N3Base/N3UIStatic.cpp
src/game/GameBase.cpp
src/game/UIHotKeyDlg.cpp
src/game/UISkillTreeDlg.cpp
src/game/UIStateBar.cpp
src/tool/N3Indoor/OrganizeView.cpp
src/tool/N3Indoor/PortalFactory.cpp
src/tool/N3Indoor/PvsObjFactory.cpp

Note that there is no need to use std::vector<char> as buffers when the
size is known as a constant value.
If the size is known, use standard arrays to reduce waste of resources.
This change also fixes an issue where some buffers had size + 1, because
we use begin and end, there is no need to account for the null
termination, since the std::string constructor will already add it.

Fix bad usages of std::vector buffers.

---

src/game/GameProcMain.cpp

This is when holding down right-button mouse cursor and dragging around.
With this fix we can now zoom out and in as in the official client.
This fix resolves: https://github.com/ko4life-net/ko/issues/92

Fix right-down mouse cursor to screen.

---

src/game/KnightOnLine.vcxproj
src/server/AIServer/AIServer.vcxproj
src/server/Aujard/Aujard.vcxproj
src/server/Ebenezer/Ebenezer.vcxproj
src/server/ItemManager/ItemManager.vcxproj
src/server/LoginServer/LoginServer.vcxproj
src/server/LoginServer/Zip.vcxproj
src/tool/KscViewer/KscViewer.vcxproj
src/tool/Launcher/Launcher/Launcher.vcxproj
src/tool/Launcher/ZipArchive/ZipArchive.vcxproj
src/tool/N3CE/N3CE.vcxproj
src/tool/N3FXE/N3FXE.vcxproj
src/tool/N3Indoor/N3Indoor.vcxproj
src/tool/N3ME/N3ME.vcxproj
src/tool/N3TexViewer/N3TexViewer.vcxproj
src/tool/N3Viewer/N3Viewer.vcxproj
src/tool/Option/Option.vcxproj
src/tool/RscTables/RscTables.vcxproj
src/tool/ServerInfoViewer/ServerInfoViewer.vcxproj
src/tool/SkyViewer/SkyViewer.vcxproj
src/tool/UIE/UIE.vcxproj

This PR cleans-up project configurations where we look for paths based on the project file in project configurations.
Apparently there is a nice way to create our own macros that can be used as a variable in project configurations.
This makes the configurations cleaner and easier to integrate new dependencies.

Simplify relative paths lookup using macros.

---

src/game/GameProcMain.cpp
src/game/UIStateBar.cpp
src/game/UIStateBar.h

This PR implements the following StateBar elements as per official:
+ Load new v1264 UI elements.
+ Display HP, MP, XP, FPS and SystemTime.
+ Display coordinates as integers instead of floats as per official.
+ Move UpdateFPS and UpdateSystemTime from Render to Tick and inline them.
+ Reorder member variables in a logical order to keep it as close as possible to the official reversed engineered client structures layout.
+ Implement changing system time visibility via chat command with "/systemtimeon" and "/systemtimeoff".
Authored by @xGuTeK and @stevewgr.

v1264 StateBar: Implements HP, MP, XP, FPS and SystemTime

---

src/server/Ebenezer/EbenezerDlg.cpp
src/server/Ebenezer/EbenezerDlg.h
src/server/Ebenezer/StdAfx.h

This PR improves loading Notice.txt file behavior. It was annoying that every time we lunch the server it complains about this file to be missing. So instead we create it as empty file, so people know of its existence and we don't see annoying error.
+ Write it with portable stl code.
+ Improve also error handling.

Create Notice.txt file if not exists.

---

src/game/GameProcMain.cpp
src/game/GameProcMain.h
src/game/UINotice.cpp
src/game/UINotice.h

+ Check for loaded components properly using assertions.
+ Trigger closing and opening now events properly for better ui transition.
+ Parse packet as how it's done officially.
+ Move TipOfTheDay to GenerateText where it's belong as per official.
+ Don't use magic numbers and use loading resources with ids from resource.h.
+ Allow also enter numpad work to close UI.
+ Simplify certain constructs.
Continuation to UINotice implementation aiming to replicate official behavior of the game.
This PR is initially authored by @xGuTeK.

Cleanup UINotice implementation (Co-authored by xGuTeK)

---

src/game/GameDef.h
src/game/GameProcMain.cpp
src/game/GameProcMain.h
src/game/GameProcedure.h
src/game/KnightOnLine.vcxproj
src/game/KnightOnLine.vcxproj.filters
src/game/UIHelp.cpp
src/game/UINotice.cpp
src/game/UIRookieTip.cpp
src/game/UIRookieTip.h

This PR implements CUIRookieTip UIF. This is when the user close either the Help or Notice UI. It also perserves the state in registry as per official.
This should be implemented exactly as per official. Note that atm we don't have chicken from level 10 quest implemented. Therefore it was added as a comment, to indicate that as soon as we implement it, we can comment it out.

Implement CUIRookieTip uif.

---

src/game/GameDef.h

After starting a Karus character one of the first things I did was kill and try to loot a Kecoon Scout. When trying to loot the monster I hit the following issue with a NULL pointer due to a missing `s_pTbl_Items_Exts` entry. Since the Item Extension 23 TBL is already present in the game assets I propose increasing the `MAX_ITEM_EXTENSION` variable to 23 in order to address the issue.
💔Thank you!

Increasing `MAX_ITEM_EXTENSION` to read in table 23 that is being reference at runtime.

---

src/game/UIImageTooltipDlg.cpp

Adding an extra string argument to match what is expected by the formatted string. I am not sure what *should* go here so added an empty string for now. I came across this issue when hovering over items in a chest dropped by a monster.
💔Thank you!

Adding an extra string argument to match what is expected by the formatted string

---

src/game/GameProcMain.cpp
src/game/UIWarp.h
src/game/res/Resource.h

Fixing issue where the wrap list would show up again after the player teleports. This is because the client isn't handling the `bySubOp` for the `N3_WARP_LIST` packet.
💔Thank you!

`N3_WARP_LIST` bySubOp switched on to prevent double warp UI from showing.

---

src/game/GameDef.h

This PR replacing the Korean item tbls with English ones coming from the v1264 USKO client.
Note that this PR needs to be merged as soon this one in ko-assets gets merged: https://github.com/ko4life-net/ko-assets/pull/9
We decided after a short discussion in discord to proceed with this approach and later sync the tbls with our current database via an automated script.

Load v1264 English item tbls.

---

src/engine/N3Base/My_3DStruct.h
src/game/GameBase.cpp
src/game/UIImageTooltipDlg.cpp

This PR implements formatting coins with commas for ui-tooltip. Note that this function can be possibly used for other scenarios, such as coins in player's inventory.
This also fixes a crash where the Texts.tbl format specifier expects a string, but was given an int. I reverted this commit, since the "fix" was wrong and the client was at fault: https://github.com/ko4life-net/ko-assets/commit/6181e4ac6be70c4c4afe31f6e216a9329f4466d7
Related to this PR: https://github.com/ko4life-net/ko-assets/pull/8
Also note that I put it near _LoadStringFromResource for now just for uniformity, as it may be used globally for other scenarios. We'll move them to some utility header file in the future once it's appriopriate in order to keep My_Struct3D.h more about 3D math.

Fix formatting coins with commas.

---

src/game/GameProcMain.cpp

Fixes improper formatting for string-id: `IDS_MSG_ATTACK_START`

Fix formatting for begin attack string id.

---

src/game/GameProcMain.cpp

This PR fixes a crash when using the `/trade` command. The size of the buffer was too small to fill all the data, which caused the client to crash.

Fix trade packet overflow using /trade cmd.

---

src/game/StdAfx.h
src/game/UIVarious.cpp
src/game/UIVarious.h

This PR cleanup nonsense amount of code duplication in UIVarious.
Also encourage mode modern C++ to avoid vulnerable usages of sprintf by including the relevant headers in the precompiled header.
+ Cleanup sprintf usages and local buffer.
+ Use CN3UIString::SetStringAsInt instead of casting it in the caller.

Cleanup code duplication in UIVarious.

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/release.yml
src/engine/N3Base/N3UIString.cpp
src/engine/N3Base/N3UIString.h
src/game/CountableItemEditDlg.cpp
src/game/GameBase.cpp
src/game/GameCursor.cpp
src/game/ItemRepairMgr.cpp
src/game/N3UIWndBase.cpp
src/game/SubProcPerTrade.cpp
src/game/UIDroppedItemDlg.cpp
src/game/UIHotKeyDlg.cpp
src/game/UIImageTooltipDlg.cpp
src/game/UIInventory.cpp
src/game/UIItemExchange.cpp
src/game/UIItemExchange.h
src/game/UILoading.cpp
src/game/UIPartyBBS.cpp
src/game/UIPerTradeDlg.cpp
src/game/UIPointInitDlg.cpp
src/game/UISkillTreeDlg.cpp
src/game/UIStateBar.cpp
src/game/UITradeEditDlg.cpp
src/game/UITradeSellBBS.cpp
src/game/UITransactionDlg.cpp
src/game/UIWareHouseDlg.cpp

This PR implements formatting coins with commas as per behavior in the official client.
I hope I didn't miss anything, but I believe it should cover most scenarios: Trade, Buy / Sell, Warehouse, Inventory, Item repair and vice versa.
Note for the reviewer:
This PR is on top of another branch that hasn't been merged yet. Please review the following two commits:
- https://github.com/ko4life-net/ko/commit/097634f7e766aa857ed86b2e74352cbed7052bd4
- https://github.com/ko4life-net/ko/commit/66d9c845964ee2d2acc0dd8f1e72d17288e38353

Implement formatting coins with commas.

---

src/game/GameProcMain.cpp

Fixes issue where item drop UI will show stay open when switching between game procedures.

Adding fix for item drop UI. This helps when the user switches to a different game procedure.

---

src/engine/N3Base/N3FXPartParticles.cpp

This fixes the GatherPoint for particles to return to a specific spot, there are 3 types spread gather and none, idk if none is ever used but I do sure know staticnova,1920 heal and some other skills use a GatherPoint. This will fix the Particles from collecting in the terrain instead of towards the char's head (1920 heal).
💔Thank you!

FX Particle Gatherpoint fix

---

config.cmd
src/engine/N3Base/N3Log.h

This PR fixes spdlog build errors and resolves the following issue: https://github.com/ko4life-net/ko/issues/216
Related PR that needs to be merged first and create a new release before merging this one: https://github.com/ko4life-net/ko-vendor/pull/11
I also enforced the config file to use that branch, so that versioning properly works and doesn't break when other repos gets updated.

Fix spdlog compile errors

---

src/game/APISocket.cpp
src/game/APISocket.h

We raise it to effectively support a total of 256 opcodes instead of 255, as 0~255 inclusive = 256 opcodes, causing it to overrun when sending/receiving the N3_TEMP_TEST packet.
- [ x Make sure you are making a pull request against the **canary branch** (left side). Also you should start *your branch* off *our canary*.
This fixes an overrun when receiving the debug packet (N3_TEMP_TEST / 0xFF) in debug builds.
We raise it to effectively support a total of 256 opcodes instead of 255, as 0~255 inclusive = 256 opcodes, which originally caused it to overrun when sending/receiving the N3_TEMP_TEST (0xFF) packet.
💔Thank you!

Fix overrun when receiving debug packet (0xFF) in debug builds

---

config.cmd
src/common/N3Utils.h
src/server/AIServer/NpcItemSet.cpp
src/server/AIServer/NpcPosSet.cpp
src/server/Aujard/DBAgent.cpp
src/server/Aujard/StdAfx.h

This PR is in combination with [this PR against the ko-db repo](https://github.com/ko4life-net/ko-db/pull/12). It updates the SQL types to binary and allows for the user to save their character information (tested locally). This is a small piece of issue #94.
💔Thank you!

Adjusting DB types for USERDATA table to start addressing issue #94

---

src/server/Aujard/DBAgent.cpp
src/server/Ebenezer/KnightsManager.cpp
src/server/LoginServer/DBProcess.cpp

These should supply the length of the query or SQL_NTS to indicate a null-terminated string, not the entire size of the buffer (https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlexecdirect-function?view=sql-server-ver16).
This only happens to behave 'correctly' in older ANSI drivers by luck; in most cases, modern drivers will report an error with the query which includes the trailing \0 bytes from the buffer.
For simplicity's sake, we can just supply SQL_NTS here and let the driver handle detection. This can be improved later to directly specify the actual length of the string when it's already known, which wsprintf() returns (and is used by most if not all instances).
💔Thank you!

Fix invalid SQLExecDirect() calls

---

src/server/AIServer/IOCPort.cpp
src/server/Ebenezer/IOCPort.cpp
src/server/LoginServer/IOCPort.cpp

This prevents race conditions where the ID is removed from the list but not restored (causing a reduced number of available socket IDs in the list), or if especially unlucky, crashes.
The socket ID list is guarded more consistently in ReceiveWorkerThread() implementations, which we essentially follow here.
Ideally I'd have an implementation to better enforce scoping for these, but for consistency with the existing code I just continue to call EnterCriticalSection() & LeaveCriticalSection() manually.
💔Thank you!

Ensure socket ID list is guarded consistently

---

config.cmd

Bump db version from 1.0.0 to 1.0.2.
Resolves the following issue: https://github.com/ko4life-net/ko/issues/223

Bump db version from 1.0.0 to 1.0.2.

---

LICENSE
src/game/KnightOnLine.vcxproj
src/server/AIServer/AIServer.vcxproj
src/server/Ebenezer/Ebenezer.vcxproj
src/tool/N3CE/N3CE.vcxproj
src/tool/N3FXE/N3FXE.vcxproj
src/tool/N3Indoor/N3Indoor.vcxproj
src/tool/PlugIn_Max/N3DExp.dsp
src/tool/PlugIn_Maya/N3E2.dsp
src/tool/PlugIn_Maya/N3E2.mak
src/tool/UIE/UIE.vcxproj

Note that we're not needing to debug DirectX and there are better ways with today's tooling to debug graphics in general. Also the actual June 2010 SDK is inconsistent and some libraries contain symbols and some don't.
This also helps reducing the size a bit of ko-vendor for the portable DirectX SDK we have there :)
Additionally removed unused usages of d3d9.lib from AIServer and Ebenezer. That's how they had it officially, but these are anyway not being used, since the server don't do graphics, rather just using the math library from d3dx9.lib.

Remove usages of debug libraries from DirectX.

---

config.cmd
docs/README.md

This PR updates docs and execution policy for current user, so that they can run powershell scripts on a freshly installed system.
Note that the reason for the execution policy change is because many users follow the steps and then they trying to run the powershell scripts, mainly in the database project, and don't understand why it is not working. Anyway a development machine needs to run scripts, so there is no need to restrict it in first place.
The cool thing is because we're setting it for the current user, there is no need for admin rights to enable it. Thanks to @xGuTeK for this advice.

Update docs and execution policy for user.

---

src/engine/N3Base/N3BaseFileAccess.cpp
src/engine/N3Base/N3Eng.cpp
src/engine/N3Base/N3Scene.cpp
src/engine/N3Base/N3Texture.cpp
src/engine/N3Base/N3UIBase.cpp
src/engine/N3Base/N3UIButton.cpp
src/engine/N3Base/N3UIEdit.cpp
src/engine/N3Base/N3UIStatic.cpp
src/tool/N3CE/N3CEDoc.cpp
src/tool/N3FXE/DlgEditFxg.cpp
src/tool/N3FXE/DlgEditPartBillBoard.cpp
src/tool/N3FXE/DlgEditPartGround.cpp
src/tool/N3FXE/DlgEditPartMesh.cpp
src/tool/N3FXE/DlgEditPartParticle.cpp
src/tool/N3FXE/DlgEditScript.cpp
src/tool/N3Indoor/MainFrm.cpp
src/tool/N3ME/DTexGroupMng.cpp
src/tool/N3ME/DTexMng.cpp
src/tool/N3ME/EventMgr.cpp
src/tool/N3ME/MainFrm.cpp
src/tool/N3ME/MapMng.cpp
src/tool/N3ME/NPCPathMgr.cpp
src/tool/PlugIn_Maya/N3E2Wrapper.cpp
src/tool/UIE/MainFrm.cpp
src/tool/UIE/UIE.cpp
src/tool/UIE/UIEDoc.cpp

This pull request refactors static references to s_szPath by using the CN3Base::PathGet getter method. This approach enhances control over s_szPath and safeguards against accidental modifications by external references.

Refactor static references to s_szPath to use CN3Base::PathGet getter.

---

src/game/Main.cpp
src/tool/N3CE/MainFrm.cpp
src/tool/N3FXE/MainFrm.cpp
src/tool/N3Indoor/MainFrm.cpp
src/tool/N3ME/MainFrm.cpp
src/tool/N3TexViewer/MainFrm.cpp
src/tool/N3Viewer/MainFrm.cpp
src/tool/ServerInfoViewer/MainFrm.cpp
src/tool/SkyViewer/MainFrm.cpp
src/tool/UIE/MainFrm.cpp

This pull request updates projects' to set the working directory to the current path, enhancing portability and consistency in asset loading.
- Configures projects to load assets relative to the current path, making applications more portable.
- Replaces `GetCurrentDirectory` (WinAPI) with `std::filesystem::current_path` in several instances to simplify code and leverage standard library functionality.

Set projects' working directories to use the current path.

---

src/engine/N3Base/N3Pond.cpp
src/engine/N3Base/N3River.cpp
src/engine/N3Base/N3River2.cpp
src/tool/N3ME/PondMng.cpp
src/tool/N3ME/RiverMng.cpp

This pull request addresses an official bug in N3ME by ensuring that the null-termination byte is correctly included when writing strings to files. This fix resolves issues caused by incorrect string length calculations, which previously led to inconsistencies during file operations.
This issue, present in official maps from the 2xxx versions, could lead to confusion or errors for users interpreting these formats.
The root cause of this bug lies in the process of reading strings from files. Specifically:
- Strings are read with 4 bytes for the string length, followed by the string content.
- If the null-termination byte is read directly into a dynamically allocated container, it becomes part of the string data, leading to failed comparisons despite visible string equality.
To remain …

Ensure correct handling of null-termination in N3ME string writing.

---

src/tool/N3TexViewer/MainFrm.cpp
src/tool/N3TexViewer/N3TexViewerDoc.cpp

This pull request enhances the usability of N3TexViewer by displaying the absolute file path of the currently opened texture in the status bar and by disabling automatic window resizing when navigating between textures. These changes improve both visibility and consistency, providing a smoother experience when working with textures.
- **Display Absolute File Path**: The status bar now shows the full path of the currently opened texture, making it easier to identify the loaded file’s location without external references.
- **Disable AdjustWindowSize on Navigation**: Previously, the window resized automatically when navigating textures with PageDown and PageUp shortcuts. This behavior often disrupted the user experience, especially with small textures (e.g., 32x32), as it shrank the window …

Improve N3TexViewer usability: show file path and disable auto-resizing on navigation.
